import peggy from "peggy";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const base = dirname(fileURLToPath(import.meta.url));
const grammarPath = resolve(base, "../src/grammar/thinklang.peggy");
const outputPath = resolve(base, "../src/parser/generated-parser.ts");

const grammar = readFileSync(grammarPath, "utf-8");

const source = peggy.generate(grammar, {
  output: "source",
  format: "es",
});

const tsOutput = `// Auto-generated by build-parser.ts — do not edit
// @ts-nocheck
/* eslint-disable */

${source}
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, tsOutput, "utf-8");
console.log(`Parser generated: ${outputPath}`);
